### ISSUE TITLE
3.10.4有一处错误

### ISSUE THREAD

**Issue by justwezzz** [mcxiaoke/mqtt#11]
![1](https://cloud.githubusercontent.com/assets/1901634/24179557/c9d0987c-0eea-11e7-8faf-b580e3550565.png)
-------------------------------------------------------------------------------------------------------------
![2](https://cloud.githubusercontent.com/assets/1901634/24179564/d2d8d010-0eea-11e7-830a-83a25696836b.png)

此处应该为UNSUBACK

**Comment by mcxiaoke** [comment]
可以在线修改，欢迎提pr

**Comment by mcxiaoke** [comment]
fixed https://github.com/mcxiaoke/mqtt/pull/12
