### ISSUE TITLE
SUBSCRIBE 的可变报头翻译有误

### ISSUE THREAD

**Issue by skybosi** [mcxiaoke/mqtt#31]
原文是：
3.8.2 Variable header
The variable header contains a Packet Identifier. Section 2.3.1 provides more information about Packet Identifiers.

你的翻译：
3.8.2 可变报头
可变报头包含客户端标识符。2.3.1 提供了有关报文标识符的更多信息。

此处客户端标识符 => 报文标识符
否则会合 CONNECT的有效载荷中的客户端标识符（clientID）混淆

**Comment by mcxiaoke** [comment]
可以在线编辑修改，欢迎提PR

**Comment by mcxiaoke** [comment]
fixed
