### ISSUE TITLE
报告一处错误

### ISSUE THREAD

**Issue by zenkoo** [mcxiaoke/mqtt#36]
你好，在MQTT-3.1.1-CN文档中的第23页3.1.2.5遗嘱标志上一行，发现一处错误，原文是这样写的“当客户端决定之后不再使用这个会话时，应该将清理会话标志设置为0最后再连接一次，然后断开连接”，应该是“当客户端决定之后不再使用这个会话时，应该将清理会话标志设置为1最后再连接一次，然后断开连接”吧？

**Comment by mcxiaoke** [comment]
最新版未发现此问题
