### ISSUE TITLE
图例标志位描述与文字不符

### ISSUE THREAD

**Issue by BetterYan** [mcxiaoke/mqtt#6]
https://mcxiaoke.gitbooks.io/mqtt-cn/content/mqtt/0301-CONNECT.html#
图例 3.4 -连接标志位 <- 有问题的表格

遗嘱QoS Will QoS
位置：连接标志的第4和第3位。

因此，图例3.4有问题

**Comment by mcxiaoke** [comment]
fixed in 64909b3b48907123bea0f226accf921eedcea83f
